### ISSUE TITLE
Squid stops indexing blocks w/o any error

### ISSUE THREAD

**Issue by osipov-mit** [subsquid/squid-sdk#273]
**Describe the bug**
Squid randomly stops indexing blocks with no errors. Only restart can help.

**To Reproduce**
Have no idea

**Screenshots**
<img width="1249" alt="image" src="https://github.com/subsquid/squid-sdk/assets/70267358/2eac42c2-aeeb-4b0f-b790-df6908714d93">

**Environment:**
 - "@subsquid/substrate-processor": "^7.2.1"
 - docker: node:20-alpine

**Comment by tmcgroul** [comment]
it is expected behaviour that processor subsribes for new blocks via `chain_subscribeFinalizedHeads` and our theory that this subscription can be buggy and hang out from time to time. i would suggest you to specify `newHeadTimeout` and see if it helps 🙂 
https://github.com/subsquid/squid-sdk/blob/master/substrate/substrate-processor/src/processor.ts#L77
